"""The compiled detection corpus the engine runs, as something the console can read.

Issue #1273: a core install loads 2,586 detection rules into fusion and fires
them, while every rule-management surface answered with an empty list. Both
API routes, and the MCP tool behind them, read the Postgres ``detection_rules``
table — and nothing in production has ever written a built-in row there. The
rules an operator was being alerted by could not be viewed, disabled or tuned.

What this module is, and is not
-------------------------------
It is a **reader**. The compiled artefacts stay the single source of truth for
what the engine runs, and ``detection_rules`` stays the single source of truth
for what a tenant has tuned. The two are merged at read time.

Seeding 2,586 rows into Postgres at boot was the other option and is worse:
the corpus is regenerated by three scripts on a different cadence from any
migration, so the table would immediately describe a different ruleset than
the engine loads, and a surface that lists rules the engine does not run is
worse than one that lists none. It is also impossible as stated —
``detection_rules.tenant_id`` is ``NOT NULL`` in every migration from
``001_init.sql`` onward, so the "platform-wide rule" the readers look for
(``tenant_id IS NULL AND is_builtin``) cannot be inserted at all.

Where the files come from
-------------------------
``services/api/app/data/detections/`` holds a packaged copy written by
``scripts/sync_packaged_detection_rulesets.py``. That is not redundancy for
its own sake: the API image is built with ``services/api`` as its Docker
context, so ``services/fusion/app/data/`` has never been reachable from it and
"just read the compiled ruleset" fails in every container. Same shape, same
fix and same parity gate as ``marketplace/index.json`` after discussion #374.

A source checkout wins over the packaged copy, so a contributor who
regenerates a ruleset sees the change without re-syncing. The gate keeps the
two byte-identical, so the preference cannot mean two different answers.

Identity
--------
A compiled rule's id is a string (``det-cloud-063``,
``sigmahq-sigma-002bdb95-…``, ``wd-port-scan``) and both response models type
``id`` as a UUID. Rather than widen the published contract, each rule gets a
deterministic UUIDv5 of its compiled id. Three properties follow, and all
three are needed:

* the same rule has the same id on every deployment and across restarts, so a
  console deep link and a saved view keep working;
* the id does not change when the tenant first tunes the rule, because the
  materialised row is inserted under exactly that UUID;
* the compiled id survives in ``provenance->>'source_id'``, which is the key
  ``services/fusion/app/services/tenant_overlay.py`` already reads. Inventing
  any other key is what would create a third source of truth.

What is deliberately absent
---------------------------
A compiled rule carries no ``description``, ``confidence`` or false-positive
history, because the artefacts do not record any. None of them is invented
here. ``confidence`` travels with ``confidence_measured=False`` so a reader
cannot mistake the placeholder for a measurement, and the two panels that
average it exclude unmeasured rules and publish how many they skipped.
"""

from __future__ import annotations

import json
import threading
import uuid
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Literal

#: ``uuid.uuid5(uuid.NAMESPACE_DNS, "detections.aisoc.invalid")``. Written as a
#: literal so the derivation cannot drift and the value is greppable. The
#: ``.invalid`` TLD is reserved by RFC 2606 and resolves nowhere, so this is a
#: namespace seed and not a claim that a host exists.
RULE_ID_NAMESPACE = uuid.UUID("9e0e07b0-20d6-52e6-a129-95a9261d34f2")

#: The language label a compiled rule reports. Deliberately not one of the six
#: ``app.services.rule_engine`` runners (``sigma``/``yara``/``kql``/``eql``/
#: ``lucene``/``regex``): the body is a ``match_when`` spec evaluated by
#: fusion's matcher, and claiming one of those would make ``/execute`` answer
#: about a language it is not running. It answers "Unsupported rule language"
#: instead, which is true.
RULE_LANGUAGE = "aisoc-match"

_HERE_PARENTS = list(Path(__file__).resolve().parents)
#: ``services/api/app`` in a checkout, ``/app/app`` in the image.
_APP_ROOT = _HERE_PARENTS[1] if len(_HERE_PARENTS) > 1 else _HERE_PARENTS[-1]
#: The repository, when there is one. Absent inside the image, where the
#: packaged copy below is the only candidate that exists.
_REPO_ROOT = _HERE_PARENTS[4] if len(_HERE_PARENTS) > 4 else _HERE_PARENTS[-1]

_PACKAGED_DIR = _APP_ROOT / "data" / "detections"
_FUSION_DIR = _REPO_ROOT / "services" / "fusion" / "app" / "data"

Kind = Literal["stateless", "windowed", "sequence"]


@dataclass(frozen=True)
class BuiltinRule:
    """One rule the detection engine loads, as the catalogue sees it."""

    source_id: str
    uuid: uuid.UUID
    name: str
    severity: str
    category: str
    kind: Kind
    #: The artefact it came from, so a disagreement can be traced to a file.
    ruleset: str
    mitre_techniques: tuple[str, ...] = ()
    product: str = ""
    service: str = ""
    slug: str = ""
    #: Upstream credit for a translated rule. DRL-1.1, which the imported
    #: corpus is licensed under, requires attribution to travel with the rule,
    #: so it is carried here and rendered as the description rather than
    #: dropped on the way to the console.
    attribution: str = ""
    #: The compiled entry exactly as the engine loads it.
    spec: dict[str, Any] | None = None

    @property
    def rule_body(self) -> str:
        """What the engine evaluates, rendered for a reader.

        The whole compiled entry rather than just ``match_when``: for a
        windowed rule the threshold, window and grouping key are as much of
        the logic as the clause is, and showing the clause alone would
        describe a rule that fires on the first event.
        """
        return json.dumps(self.spec or {}, indent=2, sort_keys=True, ensure_ascii=False)

    @property
    def description(self) -> str | None:
        """The upstream attribution, or nothing.

        The artefacts carry no per-rule prose. A sentence assembled here from
        the rule's own name would read as documentation while containing no
        information the caller did not already have.
        """
        return self.attribution or None

    @property
    def tags(self) -> list[str]:
        """Facts from the artefact, in the shape the console already filters on."""
        out = ["builtin", f"engine:{self.kind}"]
        if self.product:
            out.append(f"product:{self.product}")
        if self.service:
            out.append(f"service:{self.service}")
        return out


@dataclass(frozen=True)
class Catalogue:
    rules: tuple[BuiltinRule, ...]
    #: Repository-relative paths actually read, newest resolution first.
    sources: tuple[str, ...]
    #: Artefacts that resolved nowhere. Reported rather than absorbed: a
    #: catalogue three rules short should say so, not quietly publish a
    #: smaller total as though it were the whole corpus.
    missing: tuple[str, ...]

    @property
    def by_uuid(self) -> dict[uuid.UUID, BuiltinRule]:
        return {rule.uuid: rule for rule in self.rules}


class BuiltinCatalogueUnavailable(RuntimeError):
    """No compiled artefact could be read.

    Raised rather than returning an empty catalogue, because "the engine runs
    no rules" and "this process cannot see the file" are different statements
    and the second one is the bug #1273 reported. Callers turn this into an
    error the console renders, never into an empty list.
    """


def uuid_for(source_id: str) -> uuid.UUID:
    """The stable console id for a compiled rule id."""
    return uuid.uuid5(RULE_ID_NAMESPACE, source_id)


#: Artefact name → (kind of the rules inside, whether fusion's own directory
#: is a candidate). ``windowed_builtin_rules.json`` is generated by the sync
#: script from fusion's Python and has no counterpart under
#: ``services/fusion/app/data``.
_ARTEFACTS: tuple[tuple[str, bool], ...] = (
    ("detection_ruleset.json", True),
    ("detection_ruleset_imported.json", True),
    ("windowed_ruleset.json", True),
    ("windowed_builtin_rules.json", False),
)


def _candidates(name: str, in_fusion: bool) -> list[Path]:
    paths: list[Path] = []
    if in_fusion:
        paths.append(_FUSION_DIR / name)
        paths.append(Path("/app/services/fusion/app/data") / name)
    paths.append(_PACKAGED_DIR / name)
    return paths


def _resolve(name: str, in_fusion: bool) -> Path | None:
    for path in _candidates(name, in_fusion):
        if path.is_file():
            return path
    return None


def _attribution(spec: dict[str, Any]) -> str:
    """The upstream credit line, built from what provenance actually holds.

    Mirrors ``services/fusion/app/services/detection_engine._attribution`` so
    the sentence an operator reads in the catalogue is the sentence the alert
    carries. Assembled from the keys that are present rather than from a
    template with blanks, so a missing author reads as a shorter sentence
    instead of as an author called "".
    """
    provenance = spec.get("provenance")
    if not isinstance(provenance, dict) or not provenance.get("source"):
        return ""
    parts = [f"Translated from {provenance['source']}"]
    if provenance.get("author"):
        parts.append(f"by {provenance['author']}")
    if provenance.get("upstream_path"):
        parts.append(f"({provenance['upstream_path']})")
    licence = provenance.get("license")
    tail = f", licensed under {licence}" if licence else ""
    url = provenance.get("license_url")
    return " ".join(parts) + tail + (f" <{url}>" if url else "") + "."


def _kind(name: str, spec: dict[str, Any]) -> Kind:
    if name in ("windowed_ruleset.json", "windowed_builtin_rules.json"):
        return "sequence" if spec.get("sequence") else "windowed"
    return "stateless"


def _build(name: str, path: Path) -> list[BuiltinRule]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    rules: list[BuiltinRule] = []
    for spec in payload.get("rules") or []:
        if not isinstance(spec, dict):
            continue
        source_id = str(spec.get("id") or "").strip()
        if not source_id:
            continue
        rules.append(
            BuiltinRule(
                source_id=source_id,
                uuid=uuid_for(source_id),
                name=str(spec.get("name") or source_id),
                severity=str(spec.get("severity") or "medium"),
                category=str(spec.get("category") or "uncategorised"),
                kind=_kind(name, spec),
                ruleset=name,
                mitre_techniques=tuple(str(m).upper() for m in spec.get("mitre") or []),
                product=str(spec.get("product") or ""),
                service=str(spec.get("service") or ""),
                slug=str(spec.get("slug") or ""),
                attribution=_attribution(spec),
                spec=spec,
            )
        )
    return rules


_cache: dict[str, Any] = {"key": None, "catalogue": None}
_cache_lock = threading.Lock()


def _cache_key(resolved: list[tuple[str, Path | None]]) -> tuple[tuple[str, str, float], ...]:
    """Path plus mtime per artefact, so an edited file is picked up.

    Keyed the same way as the marketplace index: a long-lived process must not
    keep serving a corpus that was replaced underneath it.
    """
    key: list[tuple[str, str, float]] = []
    for name, path in resolved:
        key.append((name, str(path) if path else "", path.stat().st_mtime if path else 0.0))
    return tuple(key)


def builtin_catalogue() -> Catalogue:
    """Every rule the engine loads, read from whichever copy is reachable."""
    resolved = [(name, _resolve(name, in_fusion)) for name, in_fusion in _ARTEFACTS]
    key = _cache_key(resolved)

    with _cache_lock:
        cached = _cache.get("catalogue")
        if cached is not None and _cache.get("key") == key:
            return cached  # type: ignore[return-value]

        rules: list[BuiltinRule] = []
        sources: list[str] = []
        missing: list[str] = []
        for name, path in resolved:
            if path is None:
                missing.append(name)
                continue
            try:
                rules.extend(_build(name, path))
            except (OSError, ValueError) as exc:
                raise BuiltinCatalogueUnavailable(f"{path} could not be read: {exc}") from exc
            sources.append(str(path))

        if not rules:
            raise BuiltinCatalogueUnavailable(
                "no compiled detection ruleset could be read. Looked for "
                + ", ".join(str(p) for name, in_fusion in _ARTEFACTS for p in _candidates(name, in_fusion))
                + ". Run `python3 scripts/sync_packaged_detection_rulesets.py` and rebuild the API image."
            )

        catalogue = Catalogue(rules=tuple(rules), sources=tuple(sources), missing=tuple(missing))
        _cache["key"] = key
        _cache["catalogue"] = catalogue
        return catalogue


def builtin_rules() -> tuple[BuiltinRule, ...]:
    return builtin_catalogue().rules


def builtin_by_uuid(rule_id: uuid.UUID) -> BuiltinRule | None:
    try:
        return builtin_catalogue().by_uuid.get(rule_id)
    except BuiltinCatalogueUnavailable:
        return None


def builtin_by_source_id(source_id: str) -> BuiltinRule | None:
    return builtin_by_uuid(uuid_for(source_id))


def reset_cache() -> None:
    """Drop the memoised catalogue. For tests that move the artefacts."""
    with _cache_lock:
        _cache["key"] = None
        _cache["catalogue"] = None
